name: 'pr-downstream'
description: 'Create and merge downstream PR'
inputs:
  token:
    description: 'Github token with enough access rights'
    required: true
  repo:
    description: 'Repo to create PR'
    required: false
    default: 'worldr/gitops'
  branch:
    description: 'Branch to create pr in'
    required: false
    default: "main"
  change:
    description: 'What do we want to change in target repo'
    required: true
  merge:
    description: 'Do we want to merge the PR?'
    required: false
    default: "true"
  title:
    description: 'PR title'
    required: true
  body:
    description: 'PR body'
    required: true
  label:
    description: 'PR label'
    required: false
    default: "automation"
  create_tag:
    description: "Whenever to create a tag or not"
    required: false
    default: "false"
  working_directory:
    description: "Target repo local path"
    required: true
runs:
  using: "composite"
  steps:
    - run:  gh auth status
      shell: bash
      env:
        GH_TOKEN: "${{ inputs.token }}"
    - run:  ${{ inputs.change }}
      shell: bash
      working-directory: "${{inputs.working_directory}}"
      env:
        GH_TOKEN: "${{ inputs.token }}"
    - run: |
        git config --global user.email "ci@cd"
        git config --global user.name "ci"
        git checkout -b "${{inputs.branch}}"
        git add .
        git commit -m "automated"
        git push --set-upstream origin "${{inputs.branch}}"
      shell: bash
      working-directory: "${{inputs.working_directory}}"
    - id: pr
      run:  echo "::set-output name=pr-url::$(gh pr create  --title="${{inputs.title}}" --body="${{inputs.body}}")"
      shell: bash
      working-directory: "${{inputs.working_directory}}"
      env:
        GH_TOKEN: "${{ inputs.token }}"
    - run: echo "PR_URL ${{ steps.pr.outputs.pr-url }}"
      shell: bash
